import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { loadSession, describeStep } from './session.js';
import type { RecordedStep, SessionData } from './types.js';

export interface ExportTestOptions {
  sessionDir: string;
  /** Output .spec.ts path (default: <session>/flow.spec.ts). */
  out?: string;
}

const q = (s: string) => JSON.stringify(s);

/**
 * Deterministically convert a recorded session into a runnable
 * Playwright test file. No AI involved.
 */
export async function exportTest(opts: ExportTestOptions): Promise<string> {
  const sessionDir = path.resolve(opts.sessionDir);
  const session = await loadSession(sessionDir);
  const outFile = path.resolve(opts.out ?? path.join(sessionDir, 'flow.spec.ts'));
  await writeFile(outFile, buildSpec(session), 'utf8');
  return outFile;
}

export function buildSpec(session: SessionData): string {
  const lines: string[] = [];
  lines.push(`import { test, expect } from '@playwright/test';`);
  lines.push('');
  lines.push(`// Generated by FlowScribe from recorded session ${q(session.name)}`);
  lines.push(`// Recorded at ${session.startedAt} — ${session.steps.length} steps.`);
  lines.push('');
  lines.push(`test(${q(`recorded flow: ${session.name}`)}, async ({ page }) => {`);
  lines.push(`  await page.goto(${q(session.startUrl)});`);

  for (const step of session.steps) {
    const code = stepToCode(step);
    if (!code) continue;
    lines.push('');
    lines.push(`  // Step ${step.index}: ${describeStep(step).replace(/\n/g, ' ')}`);
    lines.push(...code.map((l) => `  ${l}`));
  }

  lines.push(`});`);
  lines.push('');
  return lines.join('\n');
}

function stepToCode(step: RecordedStep): string[] | null {
  switch (step.type) {
    case 'navigate': {
      // The initial goto is emitted separately; in-flow navigations become
      // URL assertions so the replay doubles as a regression test.
      if (step.index === 1) return null;
      return [`await expect(page).toHaveURL(${q(step.url)}, { timeout: 15000 });`];
    }
    case 'click':
      if (!step.selector) return null;
      return [`await page.locator(${q(step.selector)}).first().click();`];
    case 'fill':
      if (!step.selector) return null;
      return [
        `await page.locator(${q(step.selector)}).first().fill(${q(step.value ?? '')});`,
      ];
    case 'select':
      if (!step.selector) return null;
      return [
        `await page.locator(${q(step.selector)}).first().selectOption(${q(step.value ?? '')});`,
      ];
    case 'check':
      if (!step.selector) return null;
      return [
        `await page.locator(${q(step.selector)}).first().${step.checked ? 'check' : 'uncheck'}();`,
      ];
    case 'press':
      if (step.selector) {
        return [`await page.locator(${q(step.selector)}).first().press(${q(step.key ?? 'Enter')});`];
      }
      return [`await page.keyboard.press(${q(step.key ?? 'Enter')});`];
    default:
      return null;
  }
}
